### ISSUE TITLE
Show Pinned Items

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-perform#17]
If an item is pinned, it should display on the right-hand side of the screen. Multiple items can be pinned.

Pinned items depend on the navigation. Let's say A, B two folders, B is the child of A. A contains a pinned item C and B contains a pinned item D. When focusing on A in the perform view, it should display the pinned item C. But when navigating to B, it should display C and D as pinned items.  

Ideally, the user should be able to "unpin" them, and it will be saved in its custom settings (eg: localStorage).

**Comment by juancarlosfarah** [comment]
Related to https://github.com/graasp/graasp-compose/issues/180

**Comment by juancarlosfarah** [comment]
@Julien-Torrent, this is the other Pinned Item ticket (for Perform view).

**Comment by pyphilia** [comment]
closed in https://github.com/graasp/graasp-perform/pull/29
